### ISSUE TITLE
Question about CNN networks

### ISSUE THREAD

**Issue by li-wenzhan** [CHENGY12/CausalHTP#4]
Thanks for your great work! According to your description, there is a CNN branch in the framework to process the input images, but I can't find images in your "datasets" folder (only the .txt files of the trajectory sequence), and I did't find the relevant code in "models.py".

**Comment by CHENGY12** [comment]
Thanks for your attention.  We are sorry for the confusion about the CNN branch in the figure.  We just used the figure to show it is a general framework that supports image conditions.   In the experiments, the baseline methods (STGAT and STGCNN) are location-based. So that we also don't involve the image data in this repo.

**Comment by li-wenzhan** [comment]
Oh, I see. Thanks!
